import { User } from '../interfaces'

/** Dummy user data. */
export const sampleData = [
    { name: '3i Frankfurt', highlighted: false },
    { name: 'bar54', highlighted: false },
    { name: 'bristol', highlighted: false },
    { name: 'Hotel Concorde', highlighted: true },
    { name: 'Flemmings', highlighted: false },
    { name: 'Hotel Ramada', highlighted: false },
    { name: 'roomers rosenberger', highlighted: false },
    { name: 'schwarzwald', highlighted: true },
    { name: 'Berufsförderungswerk Michaelshoven', highlighted: true },
    { name: 'The Pure Basement', highlighted: false },
    { name: 'Studentenwohnheim Göggingen', highlighted: false },
    { name: 'WÜRTH', highlighted: false },
    { name: 'Hotel Oasis', highlighted: false },
    { name: '3i Frankfurt', highlighted: true },
    { name: 'bar54', highlighted: false },
    { name: 'bristol', highlighted: false },
    { name: 'Hotel Concorde', highlighted: false },
    { name: 'Flemmings', highlighted: false },
    { name: 'Hotel Ramada', highlighted: false },
    { name: 'roomers rosenberger', highlighted: false },
    { name: 'schwarzwald', highlighted: false },
    { name: 'Berufsförderungswerk Michaelshoven', highlighted: false },
    { name: 'The Pure Basement', highlighted: false },
    { name: 'Studentenwohnheim Göggingen', highlighted: false },
    { name: 'WÜRTH', highlighted: false },
    { name: 'Hotel Oasis', highlighted: false },
    { name: '3i Frankfurt', highlighted: false },
    { name: 'bar54', highlighted: true },
    { name: 'bristol', highlighted: false },
    { name: 'Hotel Concorde', highlighted: false },
    { name: 'Flemmings', highlighted: true },
    { name: 'Hotel Ramada', highlighted: false },
    { name: 'roomers rosenberger', highlighted: false },
    { name: 'schwarzwald', highlighted: false },
    { name: 'Berufsförderungswerk Michaelshoven', highlighted: true },
    { name: 'The Pure Basement', highlighted: false },
    { name: 'Studentenwohnheim Göggingen', highlighted: false },
    { name: 'WÜRTH', highlighted: false },
    { name: 'Hotel Oasis', highlighted: false },
]
